### ISSUE TITLE
[suggestion] add function to change label name

### ISSUE THREAD

**Issue by blindmanonacid** [jmuxfeldt/TabbedView2#3]
There's currently no set function for .label, only a get function. I added this to my extensions and it seems to work ok:

+ TabbedViewTab{
	label_{ arg name;
		label= name;
		tabbedView.refresh();
	}
}

I don't know how to make pull requests (yet) so hope it's ok that I just put it here.

**Comment by jmuxfeldt** [comment]
Well there IS a setter, since label is declared with <>label.  However, for all of the TabbedViewTab attributes (colors, etc) you have to refresh the tabbed view afterwords. This is as it should be, since you don't want to refresh every time you set something. You might want to set several attributes, and then refresh.

**Comment by jmuxfeldt** [comment]
I have updated the help file to mention that you must refresh.
